### ISSUE TITLE
Stop eating my crops please

### ISSUE THREAD

**Issue by KA101** [SoftMonster/KeeperRLCommunityResources#5]
https://github.com/SoftMonster/KeeperRLCommunityResources/blob/9853de9dfe1235c767650d01b7a5fd07dddd3295/Mods/Alpha36/A36BonusMod/items.txt#L293

I'd like to cache my crops and allocate them toward building a barn, but I can't, because my troops (and my Keeper >_< ) keep eating them for Satiated.  (This is with dining tables available in the feasthall, much closer than the crop field.)

Would striking this line prevent creatures from carrying off and eating entire sacks of wheat rather than devouring the steaming pigs my tables provide?

**Comment by SoftMonster** [comment]
Good idea. Try it out and send me a pull request

**Comment by KA101** [comment]
So far, adding more peasants and spot-checking creature inventories has allowed 5-6 Barns worth of grain to accumulate, so this hit back-burner.  Will check later, though.
