### ISSUE TITLE
A37TechAbsorb errors

### ISSUE THREAD

**Issue by antisocialian** [SoftMonster/KeeperRLCommunityResources#56]
Getting an error with this one:

```
Error loading mod "{A37TechAbsorb,}": ./mods/A37TechAbsorb/workshops_menu.txt: line: 4 column: - 103:
Expected "}", got "false"

Using vanilla game data
```
the errors go away after editing the file and removing the false false from the scroll creation def lines

also getting an error with line 8 of immigration.txt seems the line changed to 
```
sound = {"CREATE_IMP" 2}
```

also an error on line 78 about the companion info def of the GOBLIN_WARRIOR(and line 110 for the GOBLIN_WIZARD), seems it should be 
```
{ 0.01 { CompanionInfo {summonFreq = 0.1 creatures = { "WOLF" }}}}
```

also line 462 for the recruitment info of the DWARF_BLACKSMITH should be 
```
{ 0.0 RecruitmentInfo { "DWARVES" } 0 }
```

also line 507 for the recruitment info of the TEUTON should be 
```
{ 0.0 RecruitmentInfo { "TEUTONS" } 3 }
```

also in spells.txt on line 101 (and a few others, same thing tho) it should be 
```
sound = "SPELL_BLAST"
```

going to test if it works after this, if it has more or doesn't work at all i'll post more info.

**Comment by KA101** [comment]
Any luck?
(I've not been particularly focused on updating the A37 mods: with the release date fixed, it seems more efficient to have a stable release and then update, rather than chasing the unstable for 12 more days.  Sorry.)

**Comment by antisocialian** [comment]
it seems to work with the minor changes(at least no other errors), but i got distracted with other games so i hadn't run all the way thru a game yet.

with 1.0 coming so soon, i can see how it wouldn't be worth it to update for a37 and then again for 1.0 in a short period. I've been running it on the 1.0 dev branch and nothing has come up error-wise yet.

**Comment by KA101** [comment]
@antisocialian The 1.0 version I just merged should load up and work, if you'd be so kind as to grab a copy and let me know if it works on your end?

**Comment by KA101** [comment]
Hearing nothing, I'm guessing it works?
